services:
  - type: web
    name: track-cars-app
    env: php
    plan: free
    buildCommand: bash build.sh  # ใช้ build.sh เพื่อเรียกใช้งาน Composer และติดตั้ง dependencies
    startCommand: php -S 0.0.0.0:$PORT -t public  # ใช้คำสั่ง php เพื่อเริ่มต้นแอป
    autoDeploy: true
