services:
  - type: web
    name: php-app
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile   # ตั้ง path ของ Dockerfile
    autoDeploy: true
    envVars:
      - key: PORT
        value: 80
