services:
  - type: web
    name: track-cars-app  # สามารถเปลี่ยนเป็นชื่อที่ต้องการได้
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    autoDeploy: true
    envVars:
      - key: PORT
        value: 80
