services:
  - type: web
    name: php-app
    env: docker
    plan: free
    dockerfilePath: DockerFile  # ใช้ Dockerfile ที่เราเตรียมไว้
    autoDeploy: true
    envVars:
      - key: PORT
        value: "80"  # กำหนด port ที่ต้องใช้
