FROM php:8.2-apache

# ติดตั้งส่วนเสริม PostgreSQL
RUN docker-php-ext-install pgsql pdo pdo_pgsql

# คัดลอกไฟล์ทั้งหมดไปยัง /var/www/html
COPY . /var/www/html

# ตั้งค่าโฟลเดอร์ Document Root
WORKDIR /var/www/html
