# ใช้ PHP image พื้นฐาน
FROM php:7.4-apache

# ตั้งค่า Document Root
ENV APACHE_DOCUMENT_ROOT /var/www/html

# คัดลอกโปรเจ็กต์ไปที่ Apache document root
COPY . /var/www/html/

# ติดตั้ง PostgreSQL extension
RUN docker-php-ext-install pdo pdo_pgsql pgsql

# เปิดพอร์ต 80
EXPOSE 80

# เริ่ม Apache
CMD ["apache2-foreground"]
