# ใช้ official PHP image จาก Docker Hub
FROM php:8.1-apache

# ติดตั้ง Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# ตั้งค่า working directory
WORKDIR /var/www/html

# คัดลอกไฟล์โปรเจ็กต์ทั้งหมดไปที่ container
COPY . .

# ติดตั้ง dependencies จาก composer.json
RUN composer install

# เปิดพอร์ต 80
EXPOSE 80
